### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Vika-Derkach** [Vika-Derkach/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by DarkAnderTernopil** [comment]
You are amazing)

**Comment by Vika-Derkach** [comment]
Я знаю))

**Comment by Vika-Derkach** [comment]
I know

**Comment by Vika-Derkach** [comment]
=)
