### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Vika-Derkach** [Vika-Derkach/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by DarkAnderTernopil** [comment]
У 2008 році вступила до першого класу середньої загальноосвітньої школи № 20 міста Тернополя.
   У 2019 році закінчила 11 класів ЗОШ №20 міста Тернополя. 
   В 2019 році вступила до Тернопільського національного педагогічного університету(ТНПУ) на перший курс факультету іноземних мов, де навчаюсь на теперішній час.
